### ISSUE TITLE
后台服务运行不起来

### ISSUE THREAD

**Issue by ronalmessi** [pangxiaobin/CrawlerHot#1]
按照你描述的步骤照做了一遍，前端的页面跑起来了，但是在获取后端数据的时候出错了，GET http://127.0.0.1:8080/hot  net::ERR_CONNECTION_REFUSED，麻烦你能帮忙分析下原因吗？

**Comment by pangxiaobin** [comment]
你是本地测试运行出错 还是服务器部署出错的，请详述下你做的操作。
是自己访问出现这个，还是发链接给别人出现。

**Comment by pangxiaobin** [comment]
> 按照你描述的步骤照做了一遍，前端的页面跑起来了，但是在获取后端数据的时候出错了，GET http://127.0.0.1:8080/hot net::ERR_CONNECTION_REFUSED，麻烦你能帮忙分析下原因吗？

你是本地测试运行出错 还是服务器部署出错的，请详述下你做的操作。
是自己访问出现这个，还是发链接给别人出现。

**Comment by huaji1992** [comment]
![搜狗截图20191106184912](https://user-images.githubusercontent.com/30308645/68292149-37540800-00c6-11ea-9d4b-4e7fcd8ee8ca.png)
是前端的依赖问题吗，没有东西出来的？

**Comment by huaji1992** [comment]
![搜狗截图20191106185351](https://user-images.githubusercontent.com/30308645/68292455-daa51d00-00c6-11ea-9da4-9e9e9879651f.png)

**Comment by pangxiaobin** [comment]
> ![搜狗截图20191106184912](https://user-images.githubusercontent.com/30308645/68292149-37540800-00c6-11ea-9d4b-4e7fcd8ee8ca.png)
> 是前端的依赖问题吗，没有东西出来的？

看你发的图片的内容，应该是没有配合启动和配置nginx，如果只是想本地运行的话，可以直接点击html下的hot.htm。因为是前后分离，所以你第一个图访问的就是后端传的数据，而不是页面，需要直接点击hot.htm。
