### ISSUE TITLE
访问时没有加载数据

### ISSUE THREAD

**Issue by sexchen** [pangxiaobin/CrawlerHot#2]
![Uploading image.png…]()
在centos8中浏览没有问题，但是在局域网访问时，热榜数据没有加载
![截图_2020100615202120SS](https://user-images.githubusercontent.com/17498101/95171104-ff7aa680-07e7-11eb-8025-35864dc0bae5.png)

**Comment by sexchen** [comment]
> 在centos8中浏览没有问题，但是在关联访问时，热榜数据没有加载

好吧，我通过f12 看到jquery.js:4 GET http://127.0.0.1:8080/hot net::ERR_INVALID_HTTP_RESPONSE   我使用的宝塔不能够使用8080端口，我修改了uwsgi.ini中的端口 执行了uwsgi --ini uwsgi.ini   但是依然如此。请问应该修改什么文件修改端口呢

**Comment by pangxiaobin** [comment]
服务器端部署，需要使用uwsgi + nginx 配合使用。如果修改了uwsgi.ini 中的端口号，前端代码中访问的端口也要同步修改。

**Comment by sexchen** [comment]
emmm 

> 服务器端部署，需要使用uwsgi + nginx配合使用。如果修改了uwsgi.ini中的端口号，前端代码中访问的端口也要同步修改。

result.json我看了是有数据的，而且也按照脚本定时更新了。
uwsgi.ini的端口已经设置的和hot.html中的端口一样了，但是还是加载不出来。

我和教程有一点不一样的地方：
1.nginx是宝塔一键安装的，我将说明文档的nginx配置复制过去，网页打开会出现nginx404，宝塔默认的能加载出今日热榜，但是没有数据。
我实在是搞不懂了，可以远程协助给我支援吗？
![截图_20203125063124](https://user-images.githubusercontent.com/17498101/97104623-4e817080-16f0-11eb-889f-b381145ab8e4.png)

**Comment by pangxiaobin** [comment]
抱歉，是我的问题，少描述一些问题，我会更新下说明文档。服务器部署时hot.html请求的接口应该保证和uwsgi.ini 中配置的一样，并且其IP是服务器的ip。如果有需要可以加我qq2274858959，我远程协助下你。
